using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dalamud.Plugin.Services;
using FfxivEchoes.Events;
using FfxivEchoes.Triggers;
using FfxivEchoes.Triggers.Models;

namespace FfxivEchoes.Actions;

/// <summary>
/// <see cref="TriggerFiredEvent"/> を購読し、アクション群を該当ハンドラへ振り分ける。
/// </summary>
/// <remarks>
/// ActionDefinition.delay が指定されていれば <see cref="Task.Delay"/> で遅延実行。
/// 未知のアクションタイプは警告ログを出して無視する。
/// </remarks>
public sealed class ActionDispatcher : IDisposable
{
    private readonly Dictionary<string, IActionHandler> _handlers;
    private readonly Configuration _configuration;
    private readonly TriggerStore? _triggerStore;
    private readonly IFramework _framework;
    private readonly IPluginLog _log;
    private readonly IDisposable _subscription;
    private readonly IDisposable _combatEndSub;
    private readonly IDisposable _zoneChangeSub;
    private readonly Dictionary<string, DateTimeOffset> _recentDispatch = new();
    private readonly object _dedupGate = new();
    // 遅延アクションを Dispose 時にキャンセルする。これが無いと、プラグイン Dispose 後
    // （ホットリロード / ゾーン遷移）に遅延ハンドラがフレームスレッドへ戻り、解放済みの
    // Dalamud サービスを触って例外になる（NEW-02 フォローアップ）。
    private readonly System.Threading.CancellationTokenSource _cts = new();

    public ActionDispatcher(
        IEventBus bus,
        IEnumerable<IActionHandler> handlers,
        Configuration configuration,
        IPluginLog log,
        IFramework framework,
        TriggerStore? triggerStore = null)
    {
        _configuration = configuration;
        _triggerStore = triggerStore;
        _framework = framework;
        _log = log;
        _handlers = new Dictionary<string, IActionHandler>(StringComparer.OrdinalIgnoreCase);
        foreach (var h in handlers)
        {
            _handlers[h.Type] = h;
        }
        // overlay_corner_text は専用の隅描画を持たないため、暫定的に中央オーバーレイ（overlay_text）へ
        // ルートする。これが無いと未知アクション扱いで無音 no-op になり、しかも
        // AugmentActionsForVisibility が「visual あり」と誤判定して自動オーバーレイまで抑止していた。
        if (!_handlers.ContainsKey("overlay_corner_text") &&
            _handlers.TryGetValue("overlay_text", out var overlayText))
        {
            _handlers["overlay_corner_text"] = overlayText;
        }
        _subscription = bus.Subscribe<TriggerFiredEvent>(OnTriggerFired);
        // 戦闘終了で dedup 履歴をクリアする。ワイプ→再挑戦で開幕の正規発火が前回の履歴で
        // 誤って抑制されるのを防ぐ。
        _combatEndSub = bus.Subscribe<CombatEndedEvent>(_ =>
        {
            lock (_dedupGate) { _recentDispatch.Clear(); }
        });
        // ゾーン変更でも dedup 履歴をクリアする（別コンテンツへ移動しても前ゾーンの履歴が残らない）。
        _zoneChangeSub = bus.Subscribe<ZoneChangedEvent>(_ =>
        {
            lock (_dedupGate) { _recentDispatch.Clear(); }
        });
    }

    public void Dispose()
    {
        _cts.Cancel();
        _subscription.Dispose();
        _combatEndSub.Dispose();
        _zoneChangeSub.Dispose();
        _cts.Dispose();
    }

    private void OnTriggerFired(TriggerFiredEvent ev)
    {
        var file = _triggerStore?.GetByZone(ev.Zone);
        var sourceFiltered = AutoSafeCallPlanner.RemoveMinimapActionsForRaidWideSource(file, ev.Actions, ev.SourceEvent);
        var autoFiltered = RemoveStaleAutoGeneratedArenaViews(ev.TriggerId, sourceFiltered);
        // 補助：TTS だけのトリガーには自動で overlay_text を追加（auto_visual_for_tts）
        // 何のビジュアルも出ないと「動いてるのか？」が分からないので、デフォルト ON。
        var actions = AugmentActionsForVisibility(autoFiltered);

        foreach (var action in actions)
        {
            if (string.IsNullOrEmpty(action.Type))
            {
                continue;
            }
            if (!_handlers.TryGetValue(action.Type, out var handler))
            {
                _log.Warning("[FfxivEchoes] 未知のアクションタイプ '{Type}'（trigger={Id}）",
                    action.Type, ev.TriggerId);
                continue;
            }

            // multi-caster が同名技を複数 cast_id で同時詠唱する等で、同じ読み上げ/表示が
            // 短時間に連発するのを抑制（テキストを持つ tts / overlay_text 系のみ対象）。
            bool pass;
            lock (_dedupGate)
            {
                pass = ShouldDispatchByDedup(action.Type, action.Text, DateTimeOffset.UtcNow,
                    _recentDispatch, DefaultDedupWindowSec);
            }
            if (!pass)
            {
                _log.Debug("[FfxivEchoes] 重複抑制：type={Type} text={Text}", action.Type, action.Text);
                continue;
            }

            DispatchOne(handler, action, ev);
        }
    }

    /// <summary>読み上げ/表示テキストの重複抑制ウィンドウ（秒）。</summary>
    public const double DefaultDedupWindowSec = 3.0;

    /// <summary>
    /// 同一の読み上げ/表示テキストが短時間に連発するのを抑える（multi-caster が同名技を
    /// 複数 cast_id で同時詠唱し、同じ読み上げが何度も鳴る問題への対策）。
    /// テキストを持たない action（arena_view / timer_bar 等）は dedup しない。
    /// </summary>
    public static bool ShouldDispatchByDedup(
        string type, string? text, DateTimeOffset now,
        Dictionary<string, DateTimeOffset> recent, double windowSec)
    {
        if (string.IsNullOrEmpty(text)) return true; // 位置/タイマー系はテキストが無いので dedup しない
        var key = type + " " + text;
        if (recent.TryGetValue(key, out var last) && (now - last).TotalSeconds < windowSec)
        {
            return false; // 窓内の同一テキストは抑制（窓は初回起点。正当な再来は windowSec 経過後に通す）
        }
        recent[key] = now;
        return true;
    }

    public static IReadOnlyList<ActionDefinition> RemoveStaleAutoGeneratedArenaViews(
        string? triggerId,
        IReadOnlyList<ActionDefinition> actions)
    {
        if (string.IsNullOrWhiteSpace(triggerId) ||
            !triggerId.StartsWith("auto_cast_", StringComparison.OrdinalIgnoreCase))
        {
            return actions;
        }

        List<ActionDefinition>? filtered = null;
        for (var i = 0; i < actions.Count; i++)
        {
            var action = actions[i];
            if (IsNonUserLayoutArenaView(action))
            {
                filtered ??= new List<ActionDefinition>(actions.Take(i));
                continue;
            }

            filtered?.Add(action);
        }

        return filtered ?? actions;
    }

    private static bool IsNonUserLayoutArenaView(ActionDefinition action)
    {
        if (!string.Equals(action.Type, "arena_view", StringComparison.OrdinalIgnoreCase))
        {
            return false;
        }

        // gimmick(inner_circle/cone/outer_ring 等)を持つ arena_view は意図的な俯瞰図なので残す。
        // ArenaViewHandler は gimmick だけで正しく描画できる（gimmick 空かつ layout 無しのときだけ
        // 何も描かない）。この strip は本来「gimmick も user layout も無い＝完全に空」の旧自動予測
        // arena_view だけを除去するのが目的。gimmick を見ずに layout だけで判定すると、保存済みの
        // 正規俯瞰図（ライブ構成 被検世界「シグマ」V4.0.json の28件）まで剥がして無描画になる。
        return string.IsNullOrWhiteSpace(action.Gimmick) &&
               action.SafeZone is null &&
               (action.StrategyPositions?.Count ?? 0) == 0 &&
               (action.ObjectMarkers?.Count ?? 0) == 0 &&
               (action.AoeZones?.Count ?? 0) == 0;
    }

    /// <summary>
    /// 視認性のため、TTS のみのアクション集合に overlay_text を補完する。
    /// 既に overlay_text や arena_view が入っていれば何もしない。
    /// Configuration.AutoVisualForTts で OFF にできる。
    /// </summary>
    private List<ActionDefinition> AugmentActionsForVisibility(IReadOnlyList<ActionDefinition> original)
    {
        if (!_configuration.AutoVisualForTts) return new List<ActionDefinition>(original);

        bool hasTts = false;
        bool hasVisual = false;
        string? ttsText = null;
        foreach (var a in original)
        {
            if (string.Equals(a.Type, "tts", StringComparison.OrdinalIgnoreCase))
            {
                hasTts = true;
                ttsText ??= a.Text;
            }
            if (string.Equals(a.Type, "overlay_text", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(a.Type, "overlay_corner_text", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(a.Type, "arena_view", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(a.Type, "timer_bar", StringComparison.OrdinalIgnoreCase))
            {
                hasVisual = true;
            }
        }
        var list = new List<ActionDefinition>(original);
        if (hasTts && !hasVisual && !string.IsNullOrEmpty(ttsText))
        {
            list.Add(new ActionDefinition
            {
                Type = "overlay_text",
                Text = ttsText,
                Duration = 3.0,
                Color = "#FBBF24",
                Size = "large",
            });
        }
        return list;
    }

    private void DispatchOne(IActionHandler handler, ActionDefinition action, TriggerFiredEvent ev)
    {
        if (action.Delay <= 0)
        {
            ExecuteSafe(handler, action, ev);
            return;
        }

        // 遅延実行：fire-and-forget。例外はログのみ。
        // Delay 後の実行はフレームスレッドへ戻す。ハンドラ（arena_view 等）が ObjectTable /
        // SafeZoneContextBuilder 等の Dalamud API を触るため、スレッドプールから直接呼ぶと
        // AccessViolation / データ競合になる（NEW-02）。
        var token = _cts.Token;
        _ = Task.Run(async () =>
        {
            try
            {
                await Task.Delay(TimeSpan.FromSeconds(action.Delay), token).ConfigureAwait(false);
                if (token.IsCancellationRequested) return;
                await _framework.RunOnFrameworkThread(() => ExecuteSafe(handler, action, ev)).ConfigureAwait(false);
            }
            catch (OperationCanceledException)
            {
                // Dispose によるキャンセル。正常系。
            }
            catch (Exception ex)
            {
                _log.Error(ex, "[FfxivEchoes] 遅延実行中の例外（trigger={Id}, type={Type}）",
                    ev.TriggerId, action.Type);
            }
        }, token);
    }

    private void ExecuteSafe(IActionHandler handler, ActionDefinition action, TriggerFiredEvent ev)
    {
        try
        {
            handler.Execute(action, ev);
        }
        catch (Exception ex)
        {
            _log.Error(ex, "[FfxivEchoes] アクション実行例外（trigger={Id}, type={Type}）",
                ev.TriggerId, action.Type);
        }
    }
}
